const cityItems = {
    "国内": {
        "A": [{
            "name": "安顺",
            "namespell": "anshun",
            "captial": "AS",
            "name_en": null,
            "isHot": "N",
            "SZM": "AVA"
        }, {
            "name": "鞍山",
            "namespell": "anshan",
            "captial": "AS",
            "name_en": null,
            "isHot": "N",
            "SZM": "AOG"
        }, {
            "name": "阿尔山",
            "namespell": "aershan",
            "captial": "AES",
            "name_en": null,
            "isHot": "N",
            "SZM": "YIE"
        }, {
            "name": "安庆",
            "namespell": "anqing",
            "captial": "AQ",
            "name_en": null,
            "isHot": "N",
            "SZM": "AQG"
        }, {
            "name": "阿里",
            "namespell": "ali",
            "captial": "AL",
            "name_en": null,
            "isHot": "N",
            "SZM": "NGQ"
        }, {
            "name": "阿克苏",
            "namespell": "akesu",
            "captial": "AKS",
            "name_en": null,
            "isHot": "N",
            "SZM": "AKU"
        }],
        "B": [{
            "name": "北京",
            "namespell": "beijing",
            "captial": "BJ",
            "name_en": null,
            "isHot": "Y",
            "SZM": "PEK"
        }, {
            "name": "包头",
            "namespell": "baotou",
            "captial": "BT",
            "name_en": null,
            "isHot": "N",
            "SZM": "BAV"
        }, {
            "name": "保山",
            "namespell": "baoshan",
            "captial": "BS",
            "name_en": null,
            "isHot": "N",
            "SZM": "BSD"
        }, {
            "name": "北海",
            "namespell": "beihai",
            "captial": "BH",
            "name_en": null,
            "isHot": "N",
            "SZM": "BHY"
        }, {
            "name": "毕节",
            "namespell": "bijie",
            "captial": "BJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "BFJ"
        }, {
            "name": "百色",
            "namespell": "baise",
            "captial": "BS",
            "name_en": null,
            "isHot": "N",
            "SZM": "AEB"
        }, {
            "name": "巴彦淖尔",
            "namespell": "bayannaoer",
            "captial": "BYNE",
            "name_en": null,
            "isHot": "N",
            "SZM": "RLK"
        }],
        "C": [{
            "name": "成都",
            "namespell": "chengdu",
            "captial": "CD",
            "name_en": null,
            "isHot": "Y",
            "SZM": "CTU"
        }, {
            "name": "长沙",
            "namespell": "changsha",
            "captial": "CS",
            "name_en": null,
            "isHot": "Y",
            "SZM": "CSX"
        }, {
            "name": "长春",
            "namespell": "changchun",
            "captial": "CC",
            "name_en": null,
            "isHot": "N",
            "SZM": "CGQ"
        }, {
            "name": "常州",
            "namespell": "changzhou",
            "captial": "CZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "CZX"
        }, {
            "name": "赤峰",
            "namespell": "chifeng",
            "captial": "CF",
            "name_en": null,
            "isHot": "N",
            "SZM": "CIF"
        }, {
            "name": "长治",
            "namespell": "changzhi",
            "captial": "CZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "CIH"
        }, {
            "name": "朝阳",
            "namespell": "chaoyang",
            "captial": "CY",
            "name_en": null,
            "isHot": "N",
            "SZM": "CHG"
        }, {
            "name": "长白山",
            "namespell": "changbaishan",
            "captial": "CBS",
            "name_en": null,
            "isHot": "N",
            "SZM": "NBS"
        }, {
            "name": "常德",
            "namespell": "changde",
            "captial": "CD",
            "name_en": null,
            "isHot": "N",
            "SZM": "CGD"
        }],
        "D": [{
            "name": "大连",
            "namespell": "dalian",
            "captial": "DL",
            "name_en": null,
            "isHot": "N",
            "SZM": "DLC"
        }, {
            "name": "大理",
            "namespell": "dali",
            "captial": "DL",
            "name_en": null,
            "isHot": "N",
            "SZM": "DLU"
        }, {
            "name": "敦煌",
            "namespell": "dunhuang",
            "captial": "DH",
            "name_en": null,
            "isHot": "N",
            "SZM": "DNH"
        }, {
            "name": "大同",
            "namespell": "datong",
            "captial": "DT",
            "name_en": null,
            "isHot": "N",
            "SZM": "DAT"
        }, {
            "name": "大庆",
            "namespell": "daqing",
            "captial": "DQ",
            "name_en": null,
            "isHot": "N",
            "SZM": "DQA"
        }, {
            "name": "东营",
            "namespell": "dongying",
            "captial": "DY",
            "name_en": null,
            "isHot": "N",
            "SZM": "DOY"
        }, {
            "name": "稻城",
            "namespell": "daocheng",
            "captial": "DC",
            "name_en": null,
            "isHot": "N",
            "SZM": "DCY"
        }, {
            "name": "丹东",
            "namespell": "dandong",
            "captial": "DD",
            "name_en": null,
            "isHot": "N",
            "SZM": "DDG"
        }, {
            "name": "达州",
            "namespell": "dazhou",
            "captial": "DZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "DAX"
        }, {
            "name": "德令哈",
            "namespell": "delingha",
            "captial": "DLH",
            "name_en": null,
            "isHot": "N",
            "SZM": "HXD"
        }],
        "E": [{
            "name": "鄂尔多斯",
            "namespell": "eerduosi",
            "captial": "EEDS",
            "name_en": null,
            "isHot": "N",
            "SZM": "DSN"
        }, {
            "name": "恩施",
            "namespell": "enshi",
            "captial": "ES",
            "name_en": null,
            "isHot": "N",
            "SZM": "ENH"
        }],
        "F": [{
            "name": "福州",
            "namespell": "fuzhou",
            "captial": "FZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "FOC"
        }, {
            "name": "佛山",
            "namespell": "foshan",
            "captial": "FS",
            "name_en": null,
            "isHot": "N",
            "SZM": "FUO"
        }, {
            "name": "阜阳",
            "namespell": "fuyang",
            "captial": "FY",
            "name_en": null,
            "isHot": "N",
            "SZM": "FUG"
        }],
        "G": [{
            "name": "广州",
            "namespell": "guangzhou",
            "captial": "GZ",
            "name_en": null,
            "isHot": "Y",
            "SZM": "CAN"
        }, {
            "name": "贵阳",
            "namespell": "guiyang",
            "captial": "GY",
            "name_en": null,
            "isHot": "N",
            "SZM": "KWE"
        }, {
            "name": "桂林",
            "namespell": "guilin",
            "captial": "GL",
            "name_en": null,
            "isHot": "N",
            "SZM": "KWL"
        }, {
            "name": "赣州",
            "namespell": "ganzhou",
            "captial": "GZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "KOW"
        }, {
            "name": "格尔木",
            "namespell": "geermu",
            "captial": "GEM",
            "name_en": null,
            "isHot": "N",
            "SZM": "GOQ"
        }, {
            "name": "广元",
            "namespell": "guangyuan",
            "captial": "GY",
            "name_en": null,
            "isHot": "N",
            "SZM": "GYS"
        }, {
            "name": "泸沽湖",
            "namespell": "luguhu",
            "captial": "GH",
            "name_en": null,
            "isHot": "N",
            "SZM": "NLH"
        }],
        "H": [{
            "name": "杭州",
            "namespell": "hangzhou",
            "captial": "HZ",
            "name_en": null,
            "isHot": "Y",
            "SZM": "HGH"
        }, {
            "name": "哈尔滨",
            "namespell": "haerbin",
            "captial": "HEB",
            "name_en": null,
            "isHot": "N",
            "SZM": "HRB"
        }, {
            "name": "合肥",
            "namespell": "hefei",
            "captial": "HF",
            "name_en": null,
            "isHot": "N",
            "SZM": "HFE"
        }, {
            "name": "呼和浩特",
            "namespell": "huhehaote",
            "captial": "HHHT",
            "name_en": null,
            "isHot": "N",
            "SZM": "HET"
        }, {
            "name": "海口",
            "namespell": "haikou",
            "captial": "HK",
            "name_en": null,
            "isHot": "N",
            "SZM": "HAK"
        }, {
            "name": "海拉尔",
            "namespell": "hailaer",
            "captial": "HLE",
            "name_en": null,
            "isHot": "N",
            "SZM": "HLD"
        }, {
            "name": "淮安",
            "namespell": "huaian",
            "captial": "HA",
            "name_en": null,
            "isHot": "N",
            "SZM": "HIA"
        }, {
            "name": "黄山",
            "namespell": "huangshan",
            "captial": "HS",
            "name_en": null,
            "isHot": "N",
            "SZM": "TXN"
        }, {
            "name": "邯郸",
            "namespell": "handan",
            "captial": "HD",
            "name_en": null,
            "isHot": "N",
            "SZM": "HDG"
        }, {
            "name": "和田",
            "namespell": "hetian",
            "captial": "HT",
            "name_en": null,
            "isHot": "N",
            "SZM": "HTN"
        }, {
            "name": "汉中",
            "namespell": "hanzhong",
            "captial": "HZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "HZG"
        }, {
            "name": "黑河",
            "namespell": "heihe",
            "captial": "HH",
            "name_en": null,
            "isHot": "N",
            "SZM": "HEK"
        }, {
            "name": "哈密",
            "namespell": "hami",
            "captial": "HM",
            "name_en": null,
            "isHot": "N",
            "SZM": "HMI"
        }, {
            "name": "衡阳",
            "namespell": "hengyang",
            "captial": "HY",
            "name_en": null,
            "isHot": "N",
            "SZM": "HNY"
        }, {
            "name": "惠州",
            "namespell": "huizhou",
            "captial": "HZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "HUZ"
        }],
        "J": [{
            "name": "济南",
            "namespell": "jinan",
            "captial": "JN",
            "name_en": null,
            "isHot": "N",
            "SZM": "TNA"
        }, {
            "name": "九寨沟",
            "namespell": "jiuzhaigou",
            "captial": "JZG",
            "name_en": null,
            "isHot": "N",
            "SZM": "JZH"
        }, {
            "name": "嘉峪关",
            "namespell": "jiayuguan",
            "captial": "JYG",
            "name_en": null,
            "isHot": "N",
            "SZM": "JGN"
        }, {
            "name": "井冈山",
            "namespell": "jinggangshan",
            "captial": "JGS",
            "name_en": null,
            "isHot": "N",
            "SZM": "JGS"
        }, {
            "name": "锦州",
            "namespell": "jinzhou",
            "captial": "JZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "JNZ"
        }, {
            "name": "鸡西",
            "namespell": "jixi",
            "captial": "JX",
            "name_en": null,
            "isHot": "N",
            "SZM": "JXA"
        }, {
            "name": "济宁",
            "namespell": "jining",
            "captial": "JN",
            "name_en": null,
            "isHot": "N",
            "SZM": "JNG"
        }, {
            "name": "加格达奇",
            "namespell": "jiagedaqi",
            "captial": "JGDQ",
            "name_en": null,
            "isHot": "N",
            "SZM": "JGD"
        }, {
            "name": "九华山",
            "namespell": "jiuhuashan",
            "captial": "JHS",
            "name_en": null,
            "isHot": "N",
            "SZM": "JUH"
        }, {
            "name": "佳木斯",
            "namespell": "jiamusi",
            "captial": "JMS",
            "name_en": null,
            "isHot": "N",
            "SZM": "JMU"
        }, {
            "name": "金昌",
            "namespell": "jinchang",
            "captial": "JC",
            "name_en": null,
            "isHot": "N",
            "SZM": "JIC"
        }, {
            "name": "九江",
            "namespell": "jiujiang",
            "captial": "JJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "JIU"
        }],
        "K": [{
            "name": "昆明",
            "namespell": "kunming",
            "captial": "KM",
            "name_en": null,
            "isHot": "Y",
            "SZM": "KMG"
        }, {
            "name": "喀什",
            "namespell": "kashi",
            "captial": "KS",
            "name_en": null,
            "isHot": "N",
            "SZM": "KHG"
        }, {
            "name": "康定",
            "namespell": "kangding",
            "captial": "KD",
            "name_en": null,
            "isHot": "N",
            "SZM": "KGT"
        }, {
            "name": "库尔勒",
            "namespell": "kuerle",
            "captial": "KEL",
            "name_en": null,
            "isHot": "N",
            "SZM": "KRL"
        }, {
            "name": "凯里",
            "namespell": "kaili",
            "captial": "KL",
            "name_en": null,
            "isHot": "N",
            "SZM": "KJH"
        }, {
            "name": "库车",
            "namespell": "kuche",
            "captial": "KC",
            "name_en": null,
            "isHot": "N",
            "SZM": "KCA"
        }],
        "L": [{
            "name": "兰州",
            "namespell": "lanzhou",
            "captial": "LZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "LHW"
        }, {
            "name": "丽江",
            "namespell": "lijiang",
            "captial": "LJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "LJG"
        }, {
            "name": "临沂",
            "namespell": "linyi",
            "captial": "LY",
            "name_en": null,
            "isHot": "N",
            "SZM": "LYI"
        }, {
            "name": "拉萨",
            "namespell": "lasa",
            "captial": "LS",
            "name_en": null,
            "isHot": "N",
            "SZM": "LXA"
        }, {
            "name": "洛阳",
            "namespell": "luoyang",
            "captial": "LY",
            "name_en": null,
            "isHot": "N",
            "SZM": "LYA"
        }, {
            "name": "泸州",
            "namespell": "luzhou",
            "captial": "LZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "LZO"
        }, {
            "name": "连云港",
            "namespell": "lianyungang",
            "captial": "LYG",
            "name_en": null,
            "isHot": "N",
            "SZM": "LYG"
        }, {
            "name": "临沧",
            "namespell": "lincang",
            "captial": "LC",
            "name_en": null,
            "isHot": "N",
            "SZM": "LNJ"
        }, {
            "name": "柳州",
            "namespell": "liuzhou",
            "captial": "LZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "LZH"
        }, {
            "name": "吕梁",
            "namespell": "luliang",
            "captial": "LL",
            "name_en": null,
            "isHot": "N",
            "SZM": "LLV"
        }, {
            "name": "黎平",
            "namespell": "liping",
            "captial": "LP",
            "name_en": null,
            "isHot": "N",
            "SZM": "HZH"
        }, {
            "name": "六盘水",
            "namespell": "liupanshui",
            "captial": "LPS",
            "name_en": null,
            "isHot": "N",
            "SZM": "LPF"
        }],
        "M": [{
            "name": "芒市",
            "namespell": "mangshi",
            "captial": "MS",
            "name_en": null,
            "isHot": "N",
            "SZM": "LUM"
        }, {
            "name": "绵阳",
            "namespell": "mianyang",
            "captial": "MY",
            "name_en": null,
            "isHot": "N",
            "SZM": "MIG"
        }, {
            "name": "牡丹江",
            "namespell": "mudanjiang",
            "captial": "MDJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "MDG"
        }, {
            "name": "满洲里",
            "namespell": "manzhouli",
            "captial": "MZL",
            "name_en": null,
            "isHot": "N",
            "SZM": "NZH"
        }, {
            "name": "漠河",
            "namespell": "mohe",
            "captial": "MH",
            "name_en": null,
            "isHot": "N",
            "SZM": "OHE"
        }],
        "N": [{
            "name": "南京",
            "namespell": "nanjing",
            "captial": "NJ",
            "name_en": null,
            "isHot": "Y",
            "SZM": "NKG"
        }, {
            "name": "南昌",
            "namespell": "nanchang",
            "captial": "NC",
            "name_en": null,
            "isHot": "N",
            "SZM": "KHN"
        }, {
            "name": "宁波",
            "namespell": "ningbo",
            "captial": "NB",
            "name_en": null,
            "isHot": "N",
            "SZM": "NGB"
        }, {
            "name": "南宁",
            "namespell": "nanning",
            "captial": "NN",
            "name_en": null,
            "isHot": "N",
            "SZM": "NNG"
        }, {
            "name": "南阳",
            "namespell": "nanyang",
            "captial": "NY",
            "name_en": null,
            "isHot": "N",
            "SZM": "NNY"
        }, {
            "name": "南充",
            "namespell": "nanchong",
            "captial": "NC",
            "name_en": null,
            "isHot": "N",
            "SZM": "NAO"
        }, {
            "name": "南通",
            "namespell": "nantong",
            "captial": "NT",
            "name_en": null,
            "isHot": "N",
            "SZM": "NTG"
        }],
        "P": [{
            "name": "普洱",
            "namespell": "puer",
            "captial": "PE",
            "name_en": null,
            "isHot": "N",
            "SZM": "SYM"
        }],
        "Q": [{
            "name": "青岛",
            "namespell": "qingdao",
            "captial": "QD",
            "name_en": null,
            "isHot": "Y",
            "SZM": "TAO"
        }, {
            "name": "齐齐哈尔",
            "namespell": "qiqihaer",
            "captial": "QQHE",
            "name_en": null,
            "isHot": "N",
            "SZM": "NDG"
        }, {
            "name": "庆阳",
            "namespell": "qingyang",
            "captial": "QY",
            "name_en": null,
            "isHot": "N",
            "SZM": "IQN"
        }, {
            "name": "衢州",
            "namespell": "quzhou",
            "captial": "QZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "JUZ"
        }, {
            "name": "秦皇岛",
            "namespell": "qinhuangdao",
            "captial": "QHD",
            "name_en": null,
            "isHot": "N",
            "SZM": "SHP"
        }, {
            "name": "黔江",
            "namespell": "qianjiang",
            "captial": "QJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "JIQ"
        }, {
            "name": "泉州",
            "namespell": "quanzhou",
            "captial": "QZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "JJN"
        }],
        "R": [{
            "name": "日照",
            "namespell": "rizhao",
            "captial": "RZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "RIZ"
        }],
        "S": [{
            "name": "上海",
            "namespell": "shanghai",
            "captial": "SH",
            "name_en": null,
            "isHot": "Y",
            "SZM": "SHA"
        }, {
            "name": "深圳",
            "namespell": "shenzhen",
            "captial": "SZ",
            "name_en": null,
            "isHot": "Y",
            "SZM": "SZX"
        }, {
            "name": "三亚",
            "namespell": "sanya",
            "captial": "SY",
            "name_en": null,
            "isHot": "N",
            "SZM": "SYX"
        }, {
            "name": "沈阳",
            "namespell": "shenyang",
            "captial": "SY",
            "name_en": null,
            "isHot": "N",
            "SZM": "SHE"
        }, {
            "name": "石家庄",
            "namespell": "shijiazhuang",
            "captial": "SJZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "SJW"
        }, {
            "name": "汕头",
            "namespell": "shantou",
            "captial": "ST",
            "name_en": null,
            "isHot": "N",
            "SZM": "SWA"
        }, {
            "name": "神农架",
            "namespell": "shennongjia",
            "captial": "SNJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "HPG"
        }, {
            "name": "苏州",
            "namespell": "suzhou",
            "captial": "SZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "SZV"
        }],
        "T": [{
            "name": "太原",
            "namespell": "taiyuan",
            "captial": "TY",
            "name_en": null,
            "isHot": "Y",
            "SZM": "TYN"
        }, {
            "name": "天津",
            "namespell": "tianjin",
            "captial": "TJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "TSN"
        }, {
            "name": "腾冲",
            "namespell": "tengchong",
            "captial": "TC",
            "name_en": null,
            "isHot": "N",
            "SZM": "TCZ"
        }, {
            "name": "通辽",
            "namespell": "tongliao",
            "captial": "TL",
            "name_en": null,
            "isHot": "N",
            "SZM": "TGO"
        }, {
            "name": "台州",
            "namespell": "taizhou",
            "captial": "TZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "HYN"
        }, {
            "name": "唐山",
            "namespell": "tangshan",
            "captial": "TS",
            "name_en": null,
            "isHot": "N",
            "SZM": "TVS"
        }, {
            "name": "通化",
            "namespell": "tonghua",
            "captial": "TH",
            "name_en": null,
            "isHot": "N",
            "SZM": "TNH"
        }, {
            "name": "铜仁",
            "namespell": "tongren",
            "captial": "TR",
            "name_en": null,
            "isHot": "N",
            "SZM": "TEN"
        }],
        "W": [{
            "name": "武汉",
            "namespell": "wuhan",
            "captial": "WH",
            "name_en": null,
            "isHot": "N",
            "SZM": "WUH"
        }, {
            "name": "温州",
            "namespell": "wenzhou",
            "captial": "WZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "WNZ"
        }, {
            "name": "无锡",
            "namespell": "wuxi",
            "captial": "WX",
            "name_en": null,
            "isHot": "N",
            "SZM": "WUX"
        }, {
            "name": "乌鲁木齐",
            "namespell": "wulumuqi",
            "captial": "WLMQ",
            "name_en": null,
            "isHot": "N",
            "SZM": "URC"
        }, {
            "name": "乌海",
            "namespell": "wuhai",
            "captial": "WH",
            "name_en": null,
            "isHot": "N",
            "SZM": "WUA"
        }, {
            "name": "乌兰浩特",
            "namespell": "wulanhaote",
            "captial": "WLHT",
            "name_en": null,
            "isHot": "N",
            "SZM": "HLH"
        }, {
            "name": "文山",
            "namespell": "wenshan",
            "captial": "WS",
            "name_en": null,
            "isHot": "N",
            "SZM": "WNH"
        }, {
            "name": "武夷山",
            "namespell": "wuyishan",
            "captial": "WYS",
            "name_en": null,
            "isHot": "N",
            "SZM": "WUS"
        }, {
            "name": "威海",
            "namespell": "weihai",
            "captial": "WH",
            "name_en": null,
            "isHot": "N",
            "SZM": "WEH"
        }, {
            "name": "万州",
            "namespell": "wanzhou",
            "captial": "WZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "WXN"
        }],
        "X": [{
            "name": "西安",
            "namespell": "xian",
            "captial": "XA",
            "name_en": null,
            "isHot": "Y",
            "SZM": "XIY"
        }, {
            "name": "厦门",
            "namespell": "xiamen",
            "captial": "XM",
            "name_en": null,
            "isHot": "N",
            "SZM": "XMN"
        }, {
            "name": "西宁",
            "namespell": "xining",
            "captial": "XN",
            "name_en": null,
            "isHot": "N",
            "SZM": "XNN"
        }, {
            "name": "西双版纳",
            "namespell": "xishuangbanna",
            "captial": "XSBN",
            "name_en": null,
            "isHot": "N",
            "SZM": "JHG"
        }, {
            "name": "香格里拉",
            "namespell": "xianggelila",
            "captial": "XGLL",
            "name_en": null,
            "isHot": "N",
            "SZM": "DIG"
        }, {
            "name": "锡林浩特",
            "namespell": "xilinhaote",
            "captial": "XLHT",
            "name_en": null,
            "isHot": "N",
            "SZM": "XIL"
        }, {
            "name": "襄阳",
            "namespell": "xiangyang",
            "captial": "XY",
            "name_en": null,
            "isHot": "N",
            "SZM": "XFN"
        }, {
            "name": "西昌",
            "namespell": "xichang",
            "captial": "XC",
            "name_en": null,
            "isHot": "N",
            "SZM": "XIC"
        }, {
            "name": "兴义",
            "namespell": "xingyi",
            "captial": "XY",
            "name_en": null,
            "isHot": "N",
            "SZM": "ACX"
        }, {
            "name": "徐州",
            "namespell": "xuzhou",
            "captial": "XZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "XUZ"
        }],
        "Y": [{
            "name": "银川",
            "namespell": "yinchuan",
            "captial": "YC",
            "name_en": null,
            "isHot": "N",
            "SZM": "INC"
        }, {
            "name": "烟台",
            "namespell": "yantai",
            "captial": "YT",
            "name_en": null,
            "isHot": "N",
            "SZM": "YNT"
        }, {
            "name": "榆林",
            "namespell": "yulin",
            "captial": "YL",
            "name_en": null,
            "isHot": "N",
            "SZM": "UYN"
        }, {
            "name": "延吉",
            "namespell": "yanji",
            "captial": "YJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "YNJ"
        }, {
            "name": "运城",
            "namespell": "yuncheng",
            "captial": "YC",
            "name_en": null,
            "isHot": "N",
            "SZM": "YCU"
        }, {
            "name": "宜宾",
            "namespell": "yibin",
            "captial": "YB",
            "name_en": null,
            "isHot": "N",
            "SZM": "YBP"
        }, {
            "name": "延安",
            "namespell": "yanan",
            "captial": "YA",
            "name_en": null,
            "isHot": "N",
            "SZM": "ENY"
        }, {
            "name": "玉树",
            "namespell": "yushu",
            "captial": "YS",
            "name_en": null,
            "isHot": "N",
            "SZM": "YUS"
        }, {
            "name": "宜昌",
            "namespell": "yichang",
            "captial": "YC",
            "name_en": null,
            "isHot": "N",
            "SZM": "YIH"
        }, {
            "name": "盐城",
            "namespell": "yancheng",
            "captial": "YC",
            "name_en": null,
            "isHot": "N",
            "SZM": "YNZ"
        }, {
            "name": "伊春",
            "namespell": "yichun",
            "captial": "YC",
            "name_en": null,
            "isHot": "N",
            "SZM": "LDS"
        }, {
            "name": "永州",
            "namespell": "yongzhou",
            "captial": "YZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "LLF"
        }, {
            "name": "义乌",
            "namespell": "yiwu",
            "captial": "YW",
            "name_en": null,
            "isHot": "N",
            "SZM": "YIW"
        }, {
            "name": "伊宁",
            "namespell": "yining",
            "captial": "YN",
            "name_en": null,
            "isHot": "N",
            "SZM": "YIN"
        }, {
            "name": "扬州",
            "namespell": "yangzhou",
            "captial": "YZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "YTY"
        }],
        "Z": [{
            "name": "重庆",
            "namespell": "chongqing",
            "captial": "ZQ",
            "name_en": null,
            "isHot": "N",
            "SZM": "CKG"
        }, {
            "name": "郑州",
            "namespell": "zhengzhou",
            "captial": "ZZ",
            "name_en": null,
            "isHot": "N",
            "SZM": "CGO"
        }, {
            "name": "珠海",
            "namespell": "zhuhai",
            "captial": "ZH",
            "name_en": null,
            "isHot": "N",
            "SZM": "ZUH"
        }, {
            "name": "张家界",
            "namespell": "zhangjiajie",
            "captial": "ZJJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "DYG"
        }, {
            "name": "昭通",
            "namespell": "zhaotong",
            "captial": "ZT",
            "name_en": null,
            "isHot": "N",
            "SZM": "ZAT"
        }, {
            "name": "遵义",
            "namespell": "zunyi",
            "captial": "ZY",
            "name_en": null,
            "isHot": "N",
            "SZM": "ZYI"
        }, {
            "name": "湛江",
            "namespell": "zhanjiang",
            "captial": "ZJ",
            "name_en": null,
            "isHot": "N",
            "SZM": "ZHA"
        }, {
            "name": "舟山",
            "namespell": "zhoushan",
            "captial": "ZS",
            "name_en": null,
            "isHot": "N",
            "SZM": "HSN"
        }, {
            "name": "张家口",
            "namespell": "zhangjiakou",
            "captial": "ZJK",
            "name_en": null,
            "isHot": "N",
            "SZM": "ZQZ"
        }, {
            "name": "张掖",
            "namespell": "zhangye",
            "captial": "ZY",
            "name_en": null,
            "isHot": "N",
            "SZM": "YZY"
        }, {
            "name": "中卫",
            "namespell": "zhongwei",
            "captial": "ZW",
            "name_en": null,
            "isHot": "N",
            "SZM": "ZHY"
        }]
    },
    "港澳台": {
        "A": [{
            "name": "澳门",
            "namespell": "aomen",
            "captial": "AM",
            "name_en": "MACAU",
            "isHot": "N",
            "SZM": "MFM"
        }],
        "G": [{
            "name": "高雄",
            "namespell": "gaoxiong",
            "captial": "GX",
            "name_en": "GAOXIONG",
            "isHot": "N",
            "SZM": "KHH"
        }],
        "T": [{
            "name": "台北",
            "namespell": "taibei",
            "captial": "TB",
            "name_en": "TAIBEI",
            "isHot": "Y",
            "SZM": "TSA"
        }, {
            "name": "台中",
            "namespell": "taizhong",
            "captial": "TZ",
            "name_en": "TAIZHONG",
            "isHot": "N",
            "SZM": "RMQ"
        }, {
            "name": "台南",
            "namespell": "tainan",
            "captial": "TN",
            "name_en": "TAINAN",
            "isHot": "N",
            "SZM": "TNN"
        }],
        "X": [{
            "name": "香港",
            "namespell": "xianggang",
            "captial": "XG",
            "name_en": "HONG KONG",
            "isHot": "Y",
            "SZM": "HKG"
        }]
    }
};

module.exports = {
    cityItems
}